# Reading Recipes 

Note: Data file is recipes.csv Attached with jupyter notebook

In [3]:
import numpy as np


2. All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:

Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.

In [4]:
 cupcakes=np.array([2,0.75,2,1,0.5])


3. Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.

###########Explore yourselves how to load a csv file in numpy#######

In [5]:
import csv
from numpy import genfromtxt
recipes = genfromtxt ("recipes.csv", delimiter=",")
recipes = np.array(recipes)
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

4.Display recipes using print.
Display recipes using print.


Each row represents a different recipe. Each column represents a different ingredient.

Recipe	       Cups of Flour	Cups of Sugar	Eggs	Cups of Milk	Cups of Butter

Cupcakes	         …	              …	          …	         …	              …

Pancake	             …                …	          …	         …	              …

Cookie	             …	              …	          …	         …	              …

Bread	             …	              …	          …	         …	              …

In [6]:
print("Recipes Cups of flour Cups of sugar Eggs Cups of milk Cups of Better ")
print(f"Cupcakes {recipes[0][0]} {recipes[0][1]} {recipes[0][2]} {recipes[0][3]} {recipes[0][4]}")
print(f"Pancake  {recipes[1][0]} {recipes[1][1]} {recipes[1][2]} {recipes[1][3]} {recipes[1][4]}")
print(f"Cookie   {recipes[2][0]} {recipes[1][1]} {recipes[2][2]} {recipes[2][3]} {recipes[2][4]}")
print(f"Bread    {recipes[3][0]} {recipes[1][1]} {recipes[3][2]} {recipes[3][3]} {recipes[3][4]}")

 

Recipes Cups of flour Cups of sugar Eggs Cups of milk Cups of Better 
Cupcakes 2.0 0.75 2.0 1.0 0.5
Pancake  1.0 0.125 1.0 1.0 0.125
Cookie   2.75 0.125 1.0 0.0 1.0
Bread    4.0 0.125 2.0 2.0 0.5


5.The 3rd column represents the number of eggs that each recipe needs.

Select all elements from the 3rd column and save them to the variable eggs.

In [7]:
eggs=recipes[:,3:4]
eggs


array([[1.],
       [1.],
       [0.],
       [2.]])

6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

In [8]:
recipes_name = np.array([["Cupcakes","Pancake","Cookie","Bread"]])
print("Those recipes required only 1 egg are:",recipes_name[(eggs==1).T])
print("Those recipes required not only 1 egg are:",recipes_name[(eggs!=1).T])
eggs==1

Those recipes required only 1 egg are: ['Cupcakes' 'Pancake']
Those recipes required not only 1 egg are: ['Cookie' 'Bread']


array([[ True],
       [ True],
       [False],
       [False]])

7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.


In [9]:
#type your code here
d=recipes[3,:]
d

array([4. , 0.5, 2. , 2. , 0.5])

8.
Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

In [10]:
Cupcakes=recipes[0]
double_batch = Cupcakes*2
double_batch



array([4. , 1.5, 4. , 2. , 1. ])

9.
Create a new variable called grocery_list by adding cookies and double_batch.

In [11]:
#type your code here
Cookies = recipes[2]
grocery_list = Cookies + double_batch